controller_list:
  - name: fake_vx300s_controller
    type: $(arg fake_execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
initial:  # Define initial robot poses per group
  - group: vx300s
    pose: Home