controller_list:
  - name: vx300_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_angle
      - wrist_rotate