# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# gazebo_ros_control/pid_gains:  # add this will remove the red error of pid, but the gazebo won't work with moveit
#   joint1: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint2: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint3: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint4: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint5: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
#   joint6: {p: 0.35,  d: 0, i: 0, i_clamp: 0}
  # joint_gripper10: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper20: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper11: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}
  # joint_gripper21: {p: -0.000001,  d: -0.000002, i: 0.0, i_clamp: 0}